### PR TITLE
Command line parser fixes

### LINKED ISSUE #11: Running `dvrescue --Help` runs the program
Running `dvrescue --Help` shows the brief help page and then prints an empty XML to the screen.

Here is the output I get, testing snapshot v.0.0.0.20191113 on Ubuntu 18.04: 

```
Usage: "dvrescue [-Options...] FileName1 [Filename2...]"
"dvrescue --Help" for displaying more information.
<?xml version="1.0" encoding="UTF-8"?>
<dvrescue xmlns="https://mediaarea.net/dvrescue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://mediaarea.net/dvrescue https://raw.githubusercontent.com/mipops/dvrescue/schema-updates/tools/dvrescue.xsd" version="1.0">
	<creator>
		<program>dvrescue</program>
		<version>0.0.0.20191113</version>
	</creator>
</dvrescue>

```

(This is also true if I just run `dvrescue` alone)

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Fix #11 and related other issues.

### CODE REVIEW

File: Source/CLI/CLI_Help.cpp [hunk 1]
```diff
@@ -21,12 +21,12 @@ return_value Help(const char* Name, bool Full)
...
     if (!Full)
     {
-        cout << "\"" << Name << " --Help\" for displaying more information.\n";
+        cout << "\"" << Name << " --help\" for displaying more information.\n";
         return ReturnValue_OK;
     }
     cout << "\n"
     "Options:\n"
-    "--Help, -h         Display this help and exit.\n"
+    "--help, -h         Display this help and exit.\n"
```
Comment (ablwr) [inline Source/CLI/CLI_Help.cpp]: I'd prefer if the options were either uniformly lowercase or uppercase, but this change makes --help lowercase while leaving --Version as uppercase. I prefer lowercase overall, but I know MediaArea products tend to use uppercase. So I don't care what is chosen here, as long as it remains consistent.

Comment (dericed) [reply Source/CLI/CLI_Help.cpp]: +1 for what @ablwr said

Comment (JeromeMartinez) [reply Source/CLI/CLI_Help.cpp]: Actually `--version` is already [lowercase](https://github.com/mipops/dvrescue/blob/master/Source/CLI/CommandLine_Parser.cpp#L35), this PR puts everything in lowercase.
I fixed the misleading help part.
